---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/service-widgets

- resources:
    cpu: true
    cputemp: true
    memory: true
    disk: /

- datetime:
    text_size: xs
    format:
        dateStyle: short
        timeStyle: short
        hour12: true

- search:
    provider: google
    focus: false
    target: _self

- openmeteo:
      label: Rochester, NY # optional
      latitude: 43.1548
      longitude: -77.6156
      timezone: America/New_York # optional
      units: imperial #metric or imperial
      cache: 5 # Time in minutes to cache API responses, to stay within limits
      format: # optional, Intl.NumberFormat options
        maximumFractionDigits: 1

- stocks:
    provider: finnhub
    color: true # optional, defaults to true
    cache: 1 # optional, default caches results for 1 minute
    watchlist:
      - NVDA
      - AMD
      - TSM
      - MSFT
      - AAPL
      - MPLX
      - SPY
      - ARM